%% Nanoindentr2
% by RJS

clear
close all
clc

filepath = "C:\Users\mans3428\Downloads\LP 26-15BW Spherical Perfect Sphere.xlsx";

sheets = sheetnames(filepath);

col_disp = 1;
col_load = 2;
col_time = 3;
col_HCS = 4;
col_H = 5;
col_E = 6;

%%

TF = contains(sheets, 'Test');
SheetNames = sheets(TF);
TF_tagged = ~contains(SheetNames, ["Tagged", "Inputs"]);
SheetNames = SheetNames(TF_tagged);

%% Loop

N = length(SheetNames);

disp = nan(1, 1);
load = nan(1, 1);
time = nan(1, 1);
HCS = nan(1, 1);
H = nan(1, 1);
E = nan(1, 1);
strain = nan(1, 1);
stress = nan(1, 1);

IgnoreSheets = ["Test 001", "Test 004"];

for i = 1:N
    sheetName = SheetNames(i);
    if ismember(sheetName, IgnoreSheets)
        warning('Sheet is %s and is ignored!', sheetName);
        continue
    end
    fprintf('Wokring on %s\n', sheetName);
    output = importfileData(filepath, sheetName);

    var_disp = output(:, col_disp);
    finite_disp = isfinite(var_disp);
    var_disp = output(finite_disp, col_disp);
    var_load = output(finite_disp, col_load);
    var_time = output(finite_disp, col_time);
    var_HCS = output(finite_disp, col_HCS);
    var_H = output(finite_disp, col_H);
    var_E = output(finite_disp, col_E);

    disp = vertcat(disp, var_disp);
    load = vertcat(load, var_disp);
    time = vertcat(time, var_disp);
    HCS = vertcat(HCS, var_disp);
    H = vertcat(H, var_disp);
    E = vertcat(E, var_disp);
    
    [var_strain, var_stress] = calc_stress_strain(var_disp, var_load, var_HCS);
    
    strain = vertcat(strain, var_strain);
    stress = vertcat(stress, var_stress);
    
    plot(var_strain, var_stress, '-');
    hold on
%     drawnow;
end

%% Binning
NumBins = 100;

x = strain;
y = stress;

[Y, edges] = discretize(x, NumBins);
BinWidth = edges(2)-edges(1);
MidPoints = (edges(1:end-1)+(BinWidth/2))';

y_mean = nan(NumBins, 1);
y_std_pos = nan(NumBins, 1);
y_std_neg = nan(NumBins, 1);

LineMethod = 'mean';
BoundaryMethod = 'minmax';

for i = 1:NumBins
    TF_bin = (Y==i);
    bin_y = y(TF_bin);
    switch lower(LineMethod)
        case 'mean'
        y_mean(i) = mean(bin_y, 'omitnan');
    end
    
    switch lower(BoundaryMethod)
        case 'std'
            y_std_pos(i) = std(bin_y, 0, 'omitnan');
            y_std_neg(i) = std(bin_y, 0, 'omitnan');
        case 'minmax'
            if isfinite(y_mean(i)) == true
                y_plus = abs(y_mean(i) - max(bin_y) );
                y_minus = abs(y_mean(i) - min(bin_y) );
                y_std_pos(i) = y_plus;
                y_std_neg(i) = y_minus;
            else
                continue
            end
    end
end



%% Plotting

plot(MidPoints, y_mean, 'r-', 'LineWidth', 2);

crop_x = [0, max(MidPoints)];
withincrop = and(MidPoints >= crop_x(1), MidPoints <= crop_x(2));

new_x = MidPoints(withincrop);
new_y = y_mean(withincrop);
new_err_pos = y_std_pos(withincrop);
new_err_neg = y_std_neg(withincrop);


errorbar(new_x, new_y, new_err_neg, new_err_pos, 'r-', 'LineWidth', 2);

NiceNumbers = and(isfinite(new_x), isfinite(new_y));
new_x = new_x(NiceNumbers);
new_y = new_y(NiceNumbers);
new_err_pos = new_err_pos(NiceNumbers);
new_err_neg = new_err_neg(NiceNumbers);


Boundary_y_top = new_y + new_err_pos;
Boundary_y_bot = flipud(new_y - new_err_neg);
Boundary_x_top = new_x;
Boundary_x_bot = flipud(new_x);
Boundary_y = vertcat(Boundary_y_top, Boundary_y_bot);
Boundary_x = vertcat(Boundary_x_top, Boundary_x_bot);
% 
% k = boundary(new_x,new_y, 1);
% Boundary_x = new_x(k);
% Boundary_y = new_y(k);
Poly = polyshape(Boundary_x, Boundary_y);
hold on
plot(Poly);



%% Functions

function output = importfileData(workbookFile, sheetName, dataLines)
    %IMPORTFILE1 Import data from a spreadsheet
    %  SMREFBIGARRAYS4 = IMPORTFILE1(FILE) reads data from the first
    %  worksheet in the Microsoft Excel spreadsheet file named FILE.
    %  Returns the data as a table.
    %
    %  SMREFBIGARRAYS4 = IMPORTFILE1(FILE, SHEET) reads from the specified
    %  worksheet.
    %
    %  SMREFBIGARRAYS4 = IMPORTFILE1(FILE, SHEET, DATALINES) reads from the
    %  specified worksheet for the specified row interval(s). Specify
    %  DATALINES as a positive scalar integer or a N-by-2 array of positive
    %  scalar integers for dis-contiguous row intervals.
    %
    %  Example:
    %  SMRefBigArrayS4 = importfile1("F:\600C and Ref\2022-05-12 Batch #00001\SM_Ref_BigArray.xlsx", "Test 035", [3, 499]);
    %
    %  See also READTABLE.
    %
    % Auto-generated by MATLAB on 13-May-2022 13:30:42

    %% Input handling

    % If no sheet is specified, read first sheet
    if nargin == 1 || isempty(sheetName)
        sheetName = 1;
    end

    % If row start and end points are not specified, define defaults
    if nargin <= 2
        dataLines = [3, 499];
    end

    %% Set up the Import Options and import the data
    opts = spreadsheetImportOptions("NumVariables", 6);

    % Specify sheet and range
    opts.Sheet = sheetName;
    opts.DataRange = "B" + dataLines(1, 1) + ":G" + dataLines(1, 2);

    % Specify column names and types
    opts.VariableNames = ["DisplacementIntoSurface", "LoadOnSample", "TimeOnSample", "HarmonicContactStiffness", "Hardness", "Modulus"];
    opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

    % Import the data
    output = readtable(workbookFile, opts, "UseExcel", false);

    for idx = 2:size(dataLines, 1)
        opts.DataRange = "B" + dataLines(idx, 1) + ":G" + dataLines(idx, 2);
        tb = readtable(workbookFile, opts, "UseExcel", false);
        output = [output; tb]; %#ok<AGROW>
    end

    output = table2array(output);
end

function [var_strain, var_stress] = calc_stress_strain(var_disp, var_load, var_HCS)
    spherical_tip_radius = 2*10^-6; % In um
    coeff_Ac_1 = 2.*spherical_tip_radius./10^-9; % Diameter in nm

    hc = var_disp-(0.75.*(var_load./var_HCS).*10^6);
    Ac = (coeff_Ac_1*pi.*var_disp) - (pi.*(var_disp.^2));
    ac = (Ac./pi).^0.5;

    var_stress = (var_load./Ac).*(10^6); % In GPa
    var_strain = (4.*hc)./(3*pi.*ac);
end